In [1]:
import numpy as np

In [14]:
class MinesweeperBoard():
    def __init__(self, height, width, density):
        self.W = width
        self.H = height
        self.mines = np.zeros((width, height))
        num_mines = int(density * width * height)
        flat_indices = np.random.choice(width * height, num_mines, replace=False)
        col_indices, row_indices  = np.unravel_index(flat_indices, (width, height))
        self.mines[col_indices, row_indices] = 1
        self.seen = - np.ones((width, height))

    def reveal_tile(self, x, y):
        if self.mines[x, y] == 1:
            print("GAME OVER")
            self.show_final_board()
        else:
            neighbor_mines = self.neighbor_mines(x, y)
            if neighbor_mines == 0:
                for neighbor in self.get_neighbors(x, y):
                    self.reveal_tile(neighbor[0], neighbor[1])
                self.seen[x, y] == 0

    def neighbor_mines(self, x, y):
        neighbors = self.get_neighbors(x, y)
        mines = 0
        for neighbor in neighbors:
            if self.mines[neighbor[0], neighbor[1]] == 1:
                mines += 1
        return mines
    
    def get_neighbors(self, x, y):
        neighbors = []
        for x_prime in range(x-1, x, x+1):
            for y_prime in range(y-1, y, y+1):
                if np.any([x_prime == x and y_prime == y, x_prime < 0, y_prime < 0, x_prime >= self.W, y_prime >= self.H]):
                    continue
                neighbors.append((x, y))
        return neighbors

    def show_final_board(self):
        raise NotImplementedError()


In [12]:
board = MinesweeperBoard(10, 10, 0.5)
print(board.seen)

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
